# Generated by Django 5.2.7 on 2025-10-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customer_user_alter_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller')], max_length=20),
        ),
    ]
