# Generated by Django 5.2.7 on 2025-10-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
