# Generated by Django 5.2.7 on 2025-10-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_seller_phone_number_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
