# Generated by Django 5.2.7 on 2025-11-06 11:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_seller_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='created_at',
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
